# Uncomment the next line to define a global platform for your project
platform :ios, '17.5'

target 'CustomAdapterIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for CustomAdapterIOS
  pod 'IronSourceSDK','8.4.0.0'
  pod 'IronSourceAdQualitySDK','7.22.0'


end
