platform :ios, '15.0'

target 'CustomAdapterIOS' do
  use_frameworks!
  pod 'IronSourceSDK', '8.4.0.0'
  pod 'IronSourceAdQualitySDK', '7.22.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
